# Workflow to lint and test development branch, uses environment 'ci'

name: CI-Linting-And-Tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install repo
        run: |
          pip install -e .[dev]
      - name: Lint with precommit
        run: |
          pre-commit run --all-files

  run-tests:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "5s"

      - name: Install repo
        run: |
          pip install -e .[dev]

      - name: Test with pytest and capture coverage
        run: |
          pytest --cov=package-name --cov-report=json:coverage.json --junitxml=test.xml tests/

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          comment_mode: off
          files: |
            test.xml
